"""Report generation — clinician-ready PDF and CSV exports.

PDF uses ReportLab (free, pre-installed wheel on Streamlit Cloud).
CSV is plain pandas.
"""

import io
from datetime import datetime
from collections import Counter
import pandas as pd

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

import bodymap


def build_csv(logs) -> bytes:
    df = pd.DataFrame(logs)
    if df.empty:
        return b""
    cols = ["timestamp", "region", "pain_type", "intensity", "quality",
            "trigger", "duration_min", "note"]
    df = df[[c for c in cols if c in df.columns]]
    return df.to_csv(index=False).encode("utf-8")


def build_pdf_report(user: dict, logs: list, days: int) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2*cm, rightMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title="PainMap Report",
    )
    styles = getSampleStyleSheet()

    h1 = ParagraphStyle("H1", parent=styles["Heading1"],
                         textColor=colors.HexColor("#1A3A5C"),
                         fontSize=18, spaceAfter=12)
    h2 = ParagraphStyle("H2", parent=styles["Heading2"],
                         textColor=colors.HexColor("#2B6CB0"),
                         fontSize=13, spaceAfter=8, spaceBefore=14)
    body = ParagraphStyle("Body", parent=styles["Normal"],
                            fontSize=10, leading=14, spaceAfter=4)
    small = ParagraphStyle("Small", parent=styles["Normal"],
                             fontSize=8, textColor=colors.grey)

    story = []

    # Header
    story.append(Paragraph("PainMap Clinical Report", h1))
    story.append(Paragraph(
        f"Patient: {user['username']}  |  "
        f"Condition: {user['primary_condition'].replace('_', ' ').title()}  |  "
        f"City: {user.get('city', '—')}",
        body))
    story.append(Paragraph(
        f"Period: last {days} days  |  Generated: "
        f"{datetime.now().strftime('%Y-%m-%d %H:%M')}",
        body))
    story.append(Spacer(1, 0.4*cm))

    # Disclaimer
    story.append(Paragraph(
        "<i>This report is generated by PainMap, an open research prototype "
        "for cross-condition neurological pain self-management. It is not a "
        "medical device and is not a substitute for clinical assessment.</i>",
        small))
    story.append(Spacer(1, 0.4*cm))

    # Summary stats
    df = pd.DataFrame(logs)
    df["timestamp"] = pd.to_datetime(df["timestamp"])

    story.append(Paragraph("Summary", h2))
    summary_data = [
        ["Total logs", str(len(df))],
        ["Days with logs", str(df["timestamp"].dt.date.nunique())],
        ["Average intensity", f"{df['intensity'].mean():.1f} / 10"],
        ["Maximum intensity", f"{int(df['intensity'].max())} / 10"],
        ["Distinct regions logged", str(df["region"].nunique())],
    ]
    t = Table(summary_data, colWidths=[6*cm, 6*cm])
    t.setStyle(TableStyle([
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 10),
        ("BOTTOMPADDING", (0,0), (-1,-1), 6),
        ("LINEBELOW", (0,0), (-1,-1), 0.25, colors.HexColor("#CCCCCC")),
        ("FONTNAME", (0,0), (0,-1), "Helvetica-Bold"),
    ]))
    story.append(t)

    # By region
    story.append(Paragraph("Pain frequency by body region", h2))
    by_region = df.groupby("region").agg(
        count=("intensity", "count"),
        avg_intensity=("intensity", "mean"),
        max_intensity=("intensity", "max"),
    ).reset_index().sort_values("count", ascending=False).head(15)

    region_rows = [["Region", "# logs", "Avg /10", "Max /10"]]
    for _, row in by_region.iterrows():
        region_rows.append([
            bodymap.region_name(row["region"]),
            str(int(row["count"])),
            f"{row['avg_intensity']:.1f}",
            str(int(row["max_intensity"])),
        ])
    t2 = Table(region_rows, colWidths=[8*cm, 2.5*cm, 2.5*cm, 2.5*cm])
    t2.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1A3A5C")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ALIGN", (1,0), (-1,-1), "CENTER"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1),
            [colors.white, colors.HexColor("#F5F5F5")]),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(t2)

    # By pain type
    story.append(Paragraph("Pain types reported", h2))
    type_counts = Counter(df["pain_type"])
    type_rows = [["Pain type", "Count", "% of logs"]]
    total = len(df)
    for pt, cnt in type_counts.most_common(10):
        pct = (cnt / total * 100) if total else 0
        type_rows.append([pt.replace("_", " "), str(cnt), f"{pct:.0f}%"])
    t3 = Table(type_rows, colWidths=[8.5*cm, 3.5*cm, 3.5*cm])
    t3.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1A3A5C")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 9),
        ("ALIGN", (1,0), (-1,-1), "CENTER"),
        ("ROWBACKGROUNDS", (0,1), (-1,-1),
            [colors.white, colors.HexColor("#F5F5F5")]),
        ("BOTTOMPADDING", (0,0), (-1,-1), 5),
        ("TOPPADDING", (0,0), (-1,-1), 5),
    ]))
    story.append(t3)

    # Triggers
    triggers = [t.strip() for t in df.get("trigger", pd.Series([], dtype=str)).fillna("")
                 if t.strip()]
    if triggers:
        story.append(Paragraph("Reported triggers", h2))
        for trig, cnt in Counter(t.lower() for t in triggers).most_common(8):
            story.append(Paragraph(f"• <b>{trig}</b> — {cnt} occurrences", body))

    # Recent log entries
    story.append(PageBreak())
    story.append(Paragraph("Recent log entries (most recent first)", h2))
    recent = df.sort_values("timestamp", ascending=False).head(40)
    log_rows = [["Date", "Region", "Type", "Int.", "Quality"]]
    for _, row in recent.iterrows():
        log_rows.append([
            row["timestamp"].strftime("%Y-%m-%d %H:%M"),
            bodymap.region_name(row["region"])[:24],
            str(row["pain_type"]).replace("_", " ")[:20],
            str(int(row["intensity"])),
            (str(row.get("quality", "")) or "")[:20],
        ])
    t4 = Table(log_rows, colWidths=[3.6*cm, 4*cm, 4*cm, 1.5*cm, 4*cm])
    t4.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#1A3A5C")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTNAME", (0,1), (-1,-1), "Helvetica"),
        ("FONTSIZE", (0,0), (-1,-1), 8),
        ("ROWBACKGROUNDS", (0,1), (-1,-1),
            [colors.white, colors.HexColor("#F8F8F8")]),
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 4),
        ("TOPPADDING", (0,0), (-1,-1), 4),
    ]))
    story.append(t4)

    # Footer
    story.append(Spacer(1, 0.6*cm))
    story.append(Paragraph(
        "Generated by PainMap — Project #7 of the open-source neurological "
        "rehabilitation AI series by Samuel Tobi Oluwakoya. "
        "Contact: soluwakoyat@gmail.com",
        small))

    doc.build(story)
    return buf.getvalue()
